### ISSUE TITLE
naming attribute issue i.e. creator_id vs user_id

### ISSUE THREAD

**Issue by fgc29** [sweetlevy/Project_2_Grumpy_Cat#1]
double checking that name change worked but getting the following error.  
ActiveModel::MissingAttributeError: can't write unknown attribute `user_id'
from /Users/fgc/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.4/lib/active_record/attribute_methods/write.rb:93:in`write_attribute_with_type_cast'

**Comment by harimohanraj89** [comment]
Which relationship is this with respect to? Make sure to provide enough context around your issues.

Namely:
- Which model files are involved? (include code)
- What does your schema look like (include code snipped of relevant sections of schema)
- What are you trying to do when you encounter this error?

**Comment by fgc29** [comment]
I added it in the sticky and board models.  I'm testing my board model now getting the error.

**Comment by harimohanraj89** [comment]
You have specified which table the relationship should look at (class_name: User) but have you specified what the name of the foreign key column is? When unspecified, ActiveRecord will try its best to guess (user_id on the board model), but that guess is incorrect. You need to tell it what the foreign key should be.
