### ISSUE TITLE
Jquery UI functionality

### ISSUE THREAD

**Issue by sejenc** [sweetlevy/Project_2_Grumpy_Cat#3]
Jquery UI works locally, but is not working on the app. I put the CDN script in the head of each file. Jquery UI puts particular classes on the elements that you designate. Those classes dont appear on the elements in the app.

CDN script 

<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>

**Comment by harimohanraj89** [comment]
Include relevant code sections like we had discussed.
